from sqlalchemy import create_engine, Column, Integer, String, Float, DateTime, Boolean, Text
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from datetime import datetime

import os

DATABASE_URL = os.getenv("DATABASE_URL")
print("USING DATABASE:", DATABASE_URL)

# If running locally without env variable, use SQLite
if not DATABASE_URL:
    DATABASE_URL = "sqlite:///./integrated_accident_system.db"

# SQLite needs check_same_thread, PostgreSQL (Supabase) does not
if DATABASE_URL.startswith("sqlite"):
    engine = create_engine(
        DATABASE_URL,
        connect_args={"check_same_thread": False}
    )
else:
    engine = create_engine(DATABASE_URL, pool_pre_ping=True)

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()
class AccidentReport(Base):
    """Accident reports submitted by users"""
    __tablename__ = "accident_reports"
    
    id = Column(Integer, primary_key=True, index=True)
    latitude = Column(Float, nullable=False)
    longitude = Column(Float, nullable=False)
    severity = Column(String, nullable=False)  # Minor, Major, Fatal
    description = Column(Text)
    weather = Column(String)
    road_condition = Column(String)
    vehicle_type = Column(String)
    speed = Column(Float)
    time_of_day = Column(String)
    traffic_density = Column(String)
    reported_at = Column(DateTime, default=datetime.utcnow)
    verified = Column(Boolean, default=False)
    evidence_files = Column(Text)  # JSON string containing list of evidence file paths
    
class RiskPrediction(Base):
    """Risk predictions made by Member 1"""
    __tablename__ = "risk_predictions"
    
    id = Column(Integer, primary_key=True, index=True)
    latitude = Column(Float)
    longitude = Column(Float)
    risk_score = Column(Float)
    severity = Column(String)
    speed = Column(Float)
    weather = Column(String)
    road_condition = Column(String)
    vehicle_type = Column(String)
    time_of_day = Column(String)
    traffic_density = Column(String)
    shap_values = Column(Text)  # JSON string
    predicted_at = Column(DateTime, default=datetime.utcnow)

class NearMiss(Base):
    """Near-miss incidents detected by Member 2"""
    __tablename__ = "near_misses"
    
    id = Column(Integer, primary_key=True, index=True)
    latitude = Column(Float)
    longitude = Column(Float)
    near_miss_score = Column(Float)
    pattern_type = Column(String)  # sudden_brake, swerve, close_call
    vehicle_speed = Column(Float)
    time_gap = Column(Float)  # seconds
    detected_at = Column(DateTime, default=datetime.utcnow)
    
class RealTimeAlert(Base):
    """Real-time alerts generated by Member 3"""
    __tablename__ = "realtime_alerts"
    
    id = Column(Integer, primary_key=True, index=True)
    latitude = Column(Float)
    longitude = Column(Float)
    alert_type = Column(String)  # high_risk, near_miss, accident
    severity = Column(String)
    message = Column(Text)
    active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    expires_at = Column(DateTime)
    
class RouteAnalysis(Base):
    """Route safety analysis by Member 4"""
    __tablename__ = "route_analyses"
    
    id = Column(Integer, primary_key=True, index=True)
    start_lat = Column(Float)
    start_lng = Column(Float)
    end_lat = Column(Float)
    end_lng = Column(Float)
    route_polyline = Column(Text)  # Encoded polyline
    safety_score = Column(Float)
    total_risk_points = Column(Integer)
    high_risk_zones = Column(Text)  # JSON string
    analyzed_at = Column(DateTime, default=datetime.utcnow)

class TrafficReport(Base):
    """User-submitted traffic reports visible to all users for a limited time"""
    __tablename__ = "traffic_reports"

    id = Column(Integer, primary_key=True, index=True)
    latitude = Column(Float, nullable=False)
    longitude = Column(Float, nullable=False)
    road = Column(String, default="Unknown Road")
    severity = Column(String, default="moderate")
    description = Column(Text)
    reported_at = Column(DateTime, default=datetime.utcnow)
    expires_at = Column(DateTime)

def get_db():
    """Database dependency"""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

def init_db():
    """Initialize database tables"""
    Base.metadata.create_all(bind=engine)
    print("✅ Database initialized successfully")